<?php
return array(
    'devapi_account' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'contact_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'token' => array('varchar', 64, 'null' => 0),
        'is_remote' => array('tinyint', 4, 'default' => '0'),
        'remote_url' => array('varchar', 64),
        'new_transactions' => array('int', 11, 'default' => '0'),
        'last_update' => array('int', 11, 'default' => '0'),
        ':keys' => array(
            'devapi_account_id_uindex' => array('id', 'unique' => 1),
            'devapi_account_contact_id_index' => 'contact_id',
        ),
    ),
    'devapi_account_cash_rules' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'account_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 128),
        'target_id' => array('int', 11, 'null' => 0),
        'sort' => array('int', 11, 'null' => 0, 'default' => '0'),
        'data' => array('text'),
        ':keys' => array(
            'devapi_cash_rule_id_uindex' => array('id', 'unique' => 1),
            'devapi_cash_rule_sort_index' => 'sort',
            'devapi_cash_rule_target_id_index' => 'target_id',
            'devapi_cash_rule_account_id_index' => 'account_id',
        ),
    ),
    'devapi_account_cash_targets' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'account_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'url' => array('varchar', 64, 'null' => 0),
        'token' => array('varchar', 64, 'null' => 0),
        ':keys' => array(
            'devapi_cash_remotes_id_uindex' => array('id', 'unique' => 1),
            'devapi_cash_remotes_account_id_index' => 'account_id',
        ),
    ),
    'devapi_account_remotes' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'account_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 32, 'null' => 0),
        'params' => array('text', 'null' => 0),
        'products' => array('text', 'null' => 0),
        'start_date' => array('date'),
        ':keys' => array(
            'devapi_remote_id_uindex' => array('id', 'unique' => 1),
            'devapi_remote_account_id_index' => 'account_id',
        ),
    ),
    'devapi_settings' => array(
        'contact_id' => array('int', 11, 'null' => 0),
        'name' => array('varchar', 64, 'null' => 0),
        'value' => array('text'),
        ':keys' => array(
            'devapi_settings_contact_id_name_uindex' => array('contact_id', 'name', 'unique' => 1),
            'devapi_settings_contact_id_index' => 'contact_id',
        ),
    ),
    'devapi_transaction' => array(
        'id' => array('int', 11, 'null' => 0, 'autoincrement' => 1),
        'account_id' => array('int', 11, 'null' => 0),
        'amount' => array('float', "11,2", 'null' => 0, 'default' => '0.00'),
        'balance_after' => array('float', "11,2", 'null' => 0, 'default' => '0.00'),
        'balance_before' => array('float', "11,2", 'null' => 0, 'default' => '0.00'),
        'comment' => array('varchar', 512),
        'datetime' => array('datetime'),
        'order_id' => array('int', 11),
        'slug' => array('varchar', 64),
        'type' => array('varchar', 32),
        'discount' => array('varchar', 16),
        ':keys' => array(
            'devapi_transaction_id_uindex' => array('id', 'unique' => 1),
            'devapi_transaction_account_id_index' => 'account_id',
            'devapi_transaction_datetime_index' => 'datetime',
            'devapi_transaction_order_id_index' => 'order_id',
            'devapi_transaction_slug_index' => 'slug',
            'devapi_transaction_type_index' => 'type',
        ),
    ),
);
